set initial item of food picker to vegan to have none above to quick select
todo: Fix Bug on restart: The following NoSuchMethodError was thrown building MyHomePage(dirty, state: _MyHomePageState#9eca1):
               The method '[]' was called on null.
               Receiver: null
               Tried calling: [](null) ... probably with a loading screen and a spinner while data is grabbed, reports with graphs and pies