local storage of data working, refactored dayrows to display nothing if no suitable object exists,
todo: Fix Bug: The following NoSuchMethodError was thrown building MyHomePage(dirty, state: _MyHomePageState#9eca1):
               The method '[]' was called on null.
               Receiver: null
               Tried calling: [](null) ... probably with a loading screen and a spinner while data is grabbed, for that sake consider having an extra storage class outsourced, reports with graphs and pies